# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc0bc1345d61333ca7c166eb3a3f3bb20209e7555d4a7deac5699bdb509e854ed81a0804a32ddbb2666753b2ea6197ab0b76e52d8975602647b52121b9594450

test:
  secret_key_base: 08df859f82652214f988d0007f25f29f0ed55f5af29154bdee7aa03c42fbf149b96afc370b0fabae43695f93f1bfd83530f46c819ee99a689b0d72f35a6e3bbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
